version: '3.5'
services:
  rllibserver:
    build:
      context: .
      shm_size: '2gb'
      dockerfile: ./docker/rllib-server/Dockerfile
#    ports:
#      - "9900:9900"
#    network_mode: host

  environment:
    build:
      context: .
      shm_size: '2gb'
      dockerfile: ./Dockerfile

